
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = ""
axis = 0

[conditions.0]
name = "control"
control = true
min_chunks = 0
max_chunks = 2
targets = []
single_on = "stop_receiving"
multi_on = "unblock"
single_off = "unblock"
multi_off = "unblock"
no_seq = "unblock"
no_map = "unblock"

[conditions.1]
name = "zymolog001"
control = false
min_chunks = 0
max_chunks = 2
targets = []
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "stop_receiving"
mask = "out_zymolive001/masks"
contigs = "out_zymolive001/contigs"



