[general]
name = "aeons"                   # experiment name

[live]
device = ""                     # position on sequencer
host = "localhost"              # host of sequencing device
port = 9502                     # port of sequencing device
data_wait = 100                 # wait for X Mb data before first asm
prom = false

[optional]
bsize = 4000                    # number of reads in each deposited file
temperature = 60                # max batches during which to consider fragments
wait = 60                       # waiting time between updates in live version

[filters]                       # overwrite filters
min_seq_len = 2500
min_contig_len = 10_000
min_s1 = 200
min_map_len = 2000

[const]                         # overwrite constants
workers = 4                     # used in fastqstream read retrieval during simulations
mu = 400                        # length of anchor bases
node_size = 100                 # length of a single node in the graph in bases, determines strategy compression, hard-coded in readfish
rho = 300
alpha = 200
tetra = true                    # perform tetranucleotide frequency tests
filter_repeats = false          # perform repeat filtering
lowcov = 10                     # target for assemblies
seed = 1                        # seed for simulation shuffling                                       

[simulation]                    # simulation arguments
fq = ""
maxb = 400
binit = 5
dumptime = 200000000         
